// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://file.weifashi.cn/",
        "contact": {},
        "license": {
            "name": "AGPL-3.0 license",
            "url": "http://www.gnu.org/licenses/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/client": {
            "get": {
                "description": "获取客户端列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取客户端列表",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/interfaces.SeedReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/seed": {
            "post": {
                "description": "发送消息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "发送消息",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/interfaces.SeedReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ws": {
            "get": {
                "description": "请使用ws连接",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Websocket"
                ],
                "summary": "Websocket ws",
                "parameters": [
                    {
                        "type": "string",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "interfaces.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态, [200=成功, 400=失败, 401=未登录, 403=无相关权限, 404=请求接口不存在, 405=请求方法不允许, 500=系统错误]",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "信息",
                    "type": "string"
                }
            }
        },
        "interfaces.SeedReq": {
            "type": "object",
            "required": [
                "cmd",
                "uid"
            ],
            "properties": {
                "after": {
                    "description": "执行后执行的内容",
                    "type": "string"
                },
                "before": {
                    "description": "执行前先执行的内容",
                    "type": "string"
                },
                "cmd": {
                    "description": "执行内容",
                    "type": "string"
                },
                "path": {
                    "description": "执行文件路径",
                    "type": "string"
                },
                "uid": {
                    "description": "rid",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://localhost",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "hios",
	Description:      "hios是一款轻量级的开源在线项目文件管理工具，提供各类文档协作工具。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
